export const optionsType = [
  "Portaria",
  "Ato",
  "Relatório",
  "Edital",
  "Extrato",
  "Provimento",
  "Manifestação",
  "Deliberação",
  "Resolução",
  "Licitação",
  "Contrato",
  "Errata de Publicação",
  "Dispensa de Licitação",
  "Inexigibilidade de Licitação",
  "Avisos",
  "Resultados",
  "Concursos",
  "Súmulas",
  "circular",
];
